-- Generated from generator/demo_specs/aws-malaysia-semiconductor-maintenance.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-malaysia-semiconductor-maintenance
-- This is the schema that is actually deployed for MY_SEMICONDUCTOR_MAINTENANCE.

-- Alerts fire on the bottom tail of Equipment Uptime
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_EQUIPMENT_UPTIME) AS T
  FROM RAW.TELEMETRY
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_EQUIPMENT_UPTIME <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_EQUIPMENT_UPTIME), 2) AS AVG_EQUIPMENT_UPTIME,
  ROUND(AVG(f.KPI_SPARE_COVERAGE), 2) AS AVG_SPARE_COVERAGE,
  ROUND(AVG(f.KPI_UNPLANNED_DOWNTIME), 2) AS AVG_UNPLANNED_DOWNTIME,
  ROUND(AVG(f.KPI_PM_COMPLIANCE), 2) AS AVG_PM_COMPLIANCE
FROM RAW.TELEMETRY f
JOIN RAW.MAINTENANCE_DOCS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_EQUIPMENT_UPTIME), 2) AS AVG_EQUIPMENT_UPTIME,
  ROUND(AVG(f.KPI_SPARE_COVERAGE), 2) AS AVG_SPARE_COVERAGE,
  ROUND(AVG(f.KPI_UNPLANNED_DOWNTIME), 2) AS AVG_UNPLANNED_DOWNTIME,
  ROUND(AVG(f.KPI_PM_COMPLIANCE), 2) AS AVG_PM_COMPLIANCE
FROM RAW.TELEMETRY f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_EQUIPMENT_UPTIME) AS KPI_EQUIPMENT_UPTIME, AVG(KPI_UNPLANNED_DOWNTIME) AS KPI_UNPLANNED_DOWNTIME, AVG(KPI_PM_COMPLIANCE) AS KPI_PM_COMPLIANCE, AVG(KPI_SPARE_COVERAGE) AS KPI_SPARE_COVERAGE FROM RAW.TELEMETRY),
     en AS (SELECT SUM(KPI_TOOLS_MANAGED) AS KPI_TOOLS_MANAGED, SUM(KPI_PREDICTED_FAILURES_7D) AS KPI_PREDICTED_FAILURES_7D, SUM(KPI_PARTS_AT_RISK) AS KPI_PARTS_AT_RISK FROM RAW.MAINTENANCE_DOCS)
  SELECT 1 AS SORT_ORDER, 'Equipment Uptime' AS TITLE, KPI_EQUIPMENT_UPTIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_EQUIPMENT_UPTIME), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Unplanned Downtime' AS TITLE, KPI_UNPLANNED_DOWNTIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_UNPLANNED_DOWNTIME), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'PM Compliance' AS TITLE, KPI_PM_COMPLIANCE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PM_COMPLIANCE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Tools Managed' AS TITLE, KPI_TOOLS_MANAGED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_TOOLS_MANAGED)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Predicted Failures (7d)' AS TITLE, KPI_PREDICTED_FAILURES_7D AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PREDICTED_FAILURES_7D)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Parts at Risk' AS TITLE, KPI_PARTS_AT_RISK AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PARTS_AT_RISK)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Spare Coverage' AS TITLE, KPI_SPARE_COVERAGE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SPARE_COVERAGE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
