-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Equipment Predictive Maintenance
-- ============================================================================
USE DATABASE SEMICONDUCTOR_MAINTENANCE;
USE SCHEMA ML;

-- ML.FORECAST: RUL_FORECAST_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.RUL_FORECAST_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.REMAINING_USEFUL_LIFE'),
  SERIES_COLNAME => 'EQUIPMENT_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.RUL_FORECAST_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.RUL_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: SENSOR_DRIFT_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.SENSOR_DRIFT_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.SENSOR_DRIFT_DETECTION'),
  SERIES_COLNAME => 'SENSOR_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.SENSOR_DRIFT_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.SENSOR_DRIFT_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.SENSOR_DRIFT_DETECTION'), SERIES_COLNAME => 'SENSOR_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

