-- ============================================================================
-- 99_RESET.SQL — Reset Equipment Predictive Maintenance to clean demo state
-- ============================================================================
USE DATABASE SEMICONDUCTOR_MAINTENANCE;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_RETRAIN_MODELS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_AI SUSPEND;
ALTER TASK IF EXISTS APP.TASK_CHECK_ALERTS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.EQUIPMENT_HEALTH_SCORE REFRESH;
ALTER DYNAMIC TABLE CURATED.SENSOR_DRIFT_DETECTION REFRESH;
ALTER DYNAMIC TABLE CURATED.REMAINING_USEFUL_LIFE REFRESH;
ALTER DYNAMIC TABLE CURATED.MAINTENANCE_BACKLOG REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM SEMICONDUCTOR_MAINTENANCE.RAW.EQUIPMENT → 120
-- SELECT COUNT(*) FROM SEMICONDUCTOR_MAINTENANCE.RAW.TELEMETRY → 1000000
-- SELECT COUNT(*) FROM SEMICONDUCTOR_MAINTENANCE.CURATED.EQUIPMENT_HEALTH_SCORE WHERE STATUS = 'ALARM' → 8

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_CHECK_ALERTS RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_AI RESUME;
ALTER TASK IF EXISTS APP.TASK_RETRAIN_MODELS RESUME;
